global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # qBTC Node Metrics (if you expose metrics endpoint)
  - job_name: 'qbtc'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
          - 'bootstrap:9090'
          - 'validator1:9090'
          - 'validator2:9090'
        labels:
          network: 'mainnet'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):.*'
        target_label: instance
        replacement: '$1'

  # qBTC Health Check
  - job_name: 'qbtc-health'
    metrics_path: '/health'
    static_configs:
      - targets: 
          - 'bootstrap:8080'
          - 'validator1:8080'
          - 'validator2:8080'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):.*'
        target_label: instance
        replacement: '$1'

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'aws-server'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']