global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # qBTC Validator Node Health/Metrics
  - job_name: 'qbtc-validator'
    metrics_path: '/health'
    static_configs:
      - targets: ['validator:8080']
        labels:
          node_type: 'validator'
          network: 'mainnet'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']