global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # qBTC Health/Metrics endpoints
  - job_name: 'qbtc-nodes'
    metrics_path: '/health'
    static_configs:
      - targets: 
          - 'bootstrap:8080'
          - 'validator1:8080'
          - 'validator2:8080'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):.*'
        target_label: node
        replacement: '$1'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']